# Projects are listed alphabetically, but bitcoin- and ethereum-related projects
# have their own sections at the end.

# Non-Bitcoin / non-Ethereum


[[sections]]
name = "General"

[[sections.projects]]
name = "Aleo"
url = "https://github.com/AleoHQ"
repos = [
"AleoHQ/aleo",
"AleoHQ/snarkOS",
"AleoHQ/snarkVM",
"AleoHQ/leo",
]

[[sections.projects]]
name = "Anoma"
url = "https://github.com/anoma"
repos = [
"anoma/anoma",
"anoma/ferveo",
"anoma/masp",
"anoma/plonkup-hash",
"anoma/namada",
"anoma/vamp-ir",
"anoma/taiga",
]

[[sections.projects]]
name = "Aptos"
url = "https://github.com/aptos-labs"
repos = [
"aptos-labs/aptos-core",
]

[[sections.projects]]
name = "Casper"
url= "https://github.com/casper-network"
repos = [
"casper-network/casper-node",
"casper-network/docs",
]

[[sections.projects]]
name = "ChainSafe"
url = "https://github.com/ChainSafe"
repos = [
"ChainSafe/mina-rs",
"ChainSafe/api3-rust",
"ChainSafe/forest",
"ChainSafe/filecoindot",
]

[[sections.projects]]
name = "COMIT"
url = "https://github.com/comit-network"
repos = [
"comit-network/maia",
"comit-network/rendezvous-server",
"comit-network/xmr-btc-swap",
"comit-network/xtra-productivity",
"comit-network/waves",
]

[[sections.projects]]
name = "Concordium"
url = "https://github.com/Concordium"
repos = [
"Concordium/concordium-rust-smart-contracts",
"Concordium/concordium-wasm-smart-contracts",
"Concordium/concordium-contracts-common",
"Concordium/concordium-rust-sdk",
"Concordium/concordium-base",
"Concordium/concordium-transaction-logger",
"Concordium/concordium-euro2ccd-service",
"Concordium/concordium-use-case-examples",
"Concordium/concordium-node",
]

[[sections.projects]]
name = "Conflux"
url = "https://github.com/Conflux-Chain"
repos = [
"Conflux-Chain/conflux-rust",
]

[[sections.projects]]
name = "DarkFi"
url = "https://github.com/darkrenaissance/darkfi"
repos = [
"darkrenaissance/darkfi",
]

[[sections.projects]]
name = "Dfinity"
url = "https://github.com/dfinity"
repos = [
"dfinity/ic",
"dfinity/sdk",
"dfinity/agent-rs",
"dfinity/icx-proxy",
"dfinity/cdk-rs",
"dfinity/candid",
"dfinity/quill",
"dfinity/experimental-minting-tool",
"dfinity/vessel",
"dfinity/bitcoin-developer-preview",
"dfinity/ic-types",
]

[[sections.projects]]
name = "Dusk Network"
url = "https://github.com/dusk-network"
repos = [
"dusk-network/dusk-hamt",
"dusk-network/dusk-zerocaf",
"dusk-network/microkelvin",
"dusk-network/plonk",
"dusk-network/rusk",
"dusk-network/rusk-vm",
"dusk-network/wallet-cli",
"dusk-network/wallet-core",
]

[[sections.projects]]
name = "Elrond"
url = "https://github.com/ElrondNetwork"
repos = [
"ElrondNetwork/elrond-wasm-rs",
"ElrondNetwork/sc-dex-rs",
"ElrondNetwork/sc-nft-marketplace",
"ElrondNetwork/sc-metabonding-rs",
"ElrondNetwork/sc-bridge-elrond",
"ElrondNetwork/sc-chainlink-rs",
"ElrondNetwork/sc-delegation-rs",
"ElrondNetwork/sc-savings-account-rs",
]

[[sections.projects]]
name = "Espresso Systems"
url = "https://github.com/EspressoSystems"
repos = [
"EspressoSystems/jellyfish",
"EspressoSystems/cape",
"EspressoSystems/reef",
"EspressoSystems/seahorse",
"EspressoSystems/cap",
]

[[sections.projects]]
name = "Filecoin"
url = "https://github.com/filecoin-project"
repos = [
"filecoin-project/blstrs",
"filecoin-project/bls-signatures",
"filecoin-project/builtin-actors",
"filecoin-project/builtin-actors-bundler",
"filecoin-project/ec-gpu",
"filecoin-project/filecoin-ffi",
"filecoin-project/filecoin-phase2",
"filecoin-project/fvm-evm",
"filecoin-project/neptune",
"filecoin-project/ref-fvm",
"filecoin-project/rust-filecoin-proofs-api",
"filecoin-project/rust-fil-ffi-toolkit",
"filecoin-project/rust-fil-logger",
"filecoin-project/rust-fil-proofs",
"filecoin-project/rust-gpu-tools",
"filecoin-project/taupipp",
]

[[sections.projects]]
name = "Findora"
url = "https://github.com/FindoraNetwork"
repos = [
"FindoraNetwork/zei",
"FindoraNetwork/platform",
"FindoraNetwork/findora-scanner",
"FindoraNetwork/bp",
"FindoraNetwork/findora-exporter",
"FindoraNetwork/abcf",
"FindoraNetwork/bs3",
"FindoraNetwork/storage",
]

[[sections.projects]]
name = "Fluence"
url = "https://github.com/fluencelabs"
repos = [
"fluencelabs/marine",
"fluencelabs/aquavm",
"fluencelabs/examples",
"fluencelabs/registry",
"fluencelabs/trust-graph",
"fluencelabs/aqua-ipfs",
"fluencelabs/rust-peer",
]

[[sections.projects]]
name = "Fuel"
url = "https://github.com/FuelLabs"
repos = [
"FuelLabs/faucet",
"FuelLabs/forc-wallet",
"FuelLabs/fuel-asm",
"FuelLabs/fuel-bft",
"FuelLabs/fuel-core",
"FuelLabs/fuel-crypto",
"FuelLabs/fuel-debugger",
"FuelLabs/fuel-indexer",
"FuelLabs/fuel-merkle",
"FuelLabs/fuel-storage",
"FuelLabs/fuel-tx",
"FuelLabs/fuel-types",
"FuelLabs/fuel-vm",
"FuelLabs/fuels-rs",
"FuelLabs/fuelup",
"FuelLabs/sway",
]

[[sections.projects]]
name = "Golem"
url = "https://github.com/golemfactory"
repos = [
"golemfactory/ya-runtime-http-auth",
"golemfactory/yagna",
"golemfactory/ya-service-bus",
"golemfactory/ya-client",
"golemfactory/ya-relay",
"golemfactory/ya-runtime-sdk",
"golemfactory/ya-runtime-vm",
"golemfactory/ya-vm-file-server",
]

[[sections.projects]]
name = "Grin"
url = "https://github.com/mimblewimble/grin"
repos = [
"mimblewimble/grin",
"mimblewimble/grin-wallet",
]

[[sections.projects]]
name = "Helium"
url = "https://github.com/helium"
repos = [
"helium/gateway-rs",
"helium/semtech-udp",
"helium/helium-crypto-rs",
"helium/ecc608-linux-rs",
"helium/virtual-lorawan-device",
"helium/helium-wallet-rs",
"helium/helium-api-rs",
]

[[sections.projects]]
name = "Holochain"
url = "https://github.com/holochain"
repos = [
"holochain/holochain",
"holochain/absquic",
"holochain/launcher",
"holochain/holochain-client-rust",
"holochain/holochain-wasmer",
"holochain/hc-utils",
]

[[sections.projects]]
name = "IOTA"
url = "https://github.com/iotaledger"
repos = [
"iotaledger/bee",
"iotaledger/wallet.rs",
"iotaledger/iota.rs",
"iotaledger/identity.rs",
"iotaledger/cli-wallet",
"iotaledger/streams",
"iotaledger/stronghold.rs",
"iotaledger/chronicle.rs",
]

[[sections.projects]]
name = "Maidsafe"
url = "https://github.com/maidsafe"
repos = [
"maidsafe/sn_dbc",
"maidsafe/safe_network",
"maidsafe/qp2p",
"maidsafe/blsttc",
"maidsafe/sn_dbc_examples",
"maidsafe/sn_consensus",
"maidsafe/bls_dkg",
"maidsafe/self_encryption",
]

[[sections.projects]]
name = "MobileCoin"
url = "https://github.com/mobilecoinfoundation"
repos = [
"mobilecoinfoundation/mobilecoin",
"mobilecoinfoundation/mc-oblivious",
"mobilecoinfoundation/fog",
]

[[sections.projects]]
name = "NEAR"
url = "https://github.com/near"
repos = [
"near/workspaces-rs",
"near/nearcore",
"near/near-cli-rs",
"near/near-sdk-rs",
"near/near-jsonrpc-client-rs",
"near/near-blake2",
"near/core-contracts",
"near/near-lake-framework-rs",
"near/near-lake-indexer",
"near/borsh-rs",
"near/near-indexer-for-explorer",
"near/wasmer",
]

[[sections.projects]]
name = "Nervos"
url = "https://github.com/nervosnetwork"
repos = [
"nervosnetwork/godwoken",
"nervosnetwork/ckb",
"nervosnetwork/godwoken-scripts",
"nervosnetwork/mercury",
"nervosnetwork/ckb-vm",
"nervosnetwork/godwoken-tests",
"nervosnetwork/ckb-cli",
"nervosnetwork/molecule",
"nervosnetwork/capsule",
"nervosnetwork/ckb-indexer",
"nervosnetwork/overlord",
]

[[sections.projects]]
name = "Oasis"
url = "https://github.com/oasisprotocol"
repos = [
"oasisprotocol/oasis-sdk",
"oasisprotocol/cipher-paratime",
"oasisprotocol/emerald-paratime",
]

[[sections.projects]]
name = "Parity"
url = "https://github.com/paritytech"
repos = [
"paritytech/substrate",
"paritytech/polkadot",
"paritytech/cumulus",
"paritytech/parity-signer",
"paritytech/smoldot",
"paritytech/ink",
"paritytech/parity-common",
"paritytech/subxt",
"paritytech/jsonrpsee",
"paritytech/frontier",
"paritytech/cargo-contract",
"paritytech/substrate-contracts-node",
"paritytech/ink-playground",
"paritytech/metadata-portal",
"paritytech/parity-bridges-common",
]

[[sections.projects]]
name = "Radix"
url = "https://github.com/radixdlt"
repos = [
"radixdlt/community-scrypto-examples",
"radixdlt/foo-hack",
"radixdlt/radixdlt-scrypto",
"radixdlt/scrypto-challenges",
"radixdlt/scrypto-demos",
"radixdlt/scrypto-examples",
"radixdlt/scrypto_tutorial",
]

[[sections.projects]]
name = "Secret Network"
url = "https://github.com/scrtlabs"
repos = [
"scrtlabs/SecretNetwork",
"scrtlabs/secret-toolkit",
"scrtlabs/snip20-reference-impl",
]

[[sections.projects]]
name = "Solana"
url = "https://github.com/solana-labs"
repos = [
"solana-labs/solana",
"solana-labs/solana-program-library",
"solana-labs/solana-accountsdb-plugin-postgres",
]

[[sections.projects]]
name = "Spacemesh"
url = "https://github.com/spacemeshos"
repos = [
"spacemeshos/svm",
]

[[sections.projects]]
name = "Subspace Labs"
url = "https://github.com/subspace"
repos = [
"subspace/subspace",
]

[[sections.projects]]
name = "Sui"
url = "https://github.com/MystenLabs"
repos = [
"MystenLabs/sui",
"MystenLabs/narwhal",
]

[[sections.projects]]
name = "TezEdge"
url = "https://github.com/tezedge"
repos = [
"tezedge/tezedge",
"tezedge/tezedge-snapshots",
"tezedge/tezedge-tui",
]

[[sections.projects]]
name = "Zcash"
url = "https://github.com/zcash"
repos = [
"ZcashFoundation/zebra",
"zcash/halo2",
"zcash/incrementalmerkletree",
"zcash/librustzcash",
"zcash/orchard",
"zcash/pasta_curves",
]


# Bitcoin

[[sections]]
name = "Bitcoin"

[[sections.projects]]
name = "BDK"
url = "https://github.com/bitcoindevkit"
repos = [
"bitcoindevkit/bdk",
"bitcoindevkit/bdk-cli",
"bitcoindevkit/bdk-ffi",
"bitcoindevkit/rust-hwi",
"bitcoindevkit/rust-electrum-client",
]

[[sections.projects]]
name = "Bitmask"
url = "https://github.com/diba-io/bitmask-core"
repos = [
"diba-io/bitmask-core",
]

[[sections.projects]]
name = "Electrs"
url = "https://github.com/romanz"
repos = [
"romanz/electrs",
]

[[sections.projects]]
name = "Internet2"
url = "https://github.com/Internet2-WG"
repos = [
"Internet2-WG/rust-aluvm",
"Internet2-WG/rust-internet2",
"Internet2-WG/rust-microservices",
"Internet2-WG/stenc",
]

[[sections.projects]]
name = "LDK"
url = "https://github.com/lightningdevkit"
repos = [
"lightningdevkit/rust-lightning",
"lightningdevkit/ldk-sample",
"lightningdevkit/ldk-c-bindings",
]

[[sections.projects]]
name = "LNP/BP"
url = "https://github.com/LNP-BP"
repos = [
"LNP-BP/client_side_validation",
"LNP-BP/rust-lnpbp",
"LNP-BP/invoices",
"rust-amplify/rust-amplify",
"BP-WG/bp-node",
"BP-WG/bp-core",
"BP-WG/descriptor-wallet",
"BP-WG/rust-psbt",
]

[[sections.projects]]
name = "LNP WG"
url = "https://github.com/LNP-WG"
repos = [
"LNP-WG/lnp-core",
"LNP-WG/lnp-node",
"LNP-WG/lightning_encoding",
"LNP-WG/ln-types",
]

[[sections.projects]]
name = "Nakamoto"
url = "https://github.com/cloudhead/nakamoto"
repos = [
"cloudhead/nakamoto",
]

[[sections.projects]]
name = "MyCitadel"
url = "https://github.com/orgs/mycitadel"
repos = [
"mycitadel/citadel-runtime",
"mycitadel/libcitadel",
"mycitadel/mycitadel-desktop",
"mycitadel/mycitadel-node",
]

[[sections.projects]]
name = "Nomic"
url = "https://github.com/nomic-io"
repos = [
"nomic-io/nomic",
"nomic-io/merk",
"nomic-io/orga",
"nomic-io/abci2",
"nomic-io/ed",
]

[[sections.projects]]
name = "RGB"
url = "https://github.com/RGB-WG"
repos = [
"RGB-WG/rgb-core",
"RGB-WG/rgb-node",
"RGB-WG/rust-rgb20",
]

[[sections.projects]]
name = "Rust Bitcoin"
url = "https://github.com/rust-bitcoin"
repos = [
"rust-bitcoin/rust-bitcoin",
"rust-bitcoin/rust-secp256k1",
"rust-bitcoin/rust-miniscript",
"rust-bitcoin/rust-wallet",
"rust-bitcoin/rust-bitcoincore-rpc",
"rust-bitcoin/rust-bech32-bitcoin",
"rust-bitcoin/murmel",
"rust-bitcoin/rust-bip39",
"rust-bitcoin/bitcoin_hashes",
"jean-airoldie/zeromq-src-rs",
]

[[sections.projects]]
name = "Rust Simplicity"
url = "https://github.com/ElementsProject/rust-simplicity"
repos = [
"ElementsProject/rust-simplicity",
]

[[sections.projects]]
name = "Sapio"
url = "https://github.com/sapio-lang"
repos = [
"sapio-lang/sapio",
]

[[sections.projects]]
name = "Talaia"
url = "https://github.com/talaia-labs"
repos = [
"talaia-labs/rust-teos",
]


# Ethereum

[[sections]]
name = "Ethereum"

[[sections.projects]]
name = "Ethers-rs"
url = "https://github.com/gakonst/ethers-rs"
repos = [
"gakonst/ethers-rs",
]

[[sections.projects]]
name = "Foundry"
url = "https://github.com/foundry-rs"
repos = [
"foundry-rs/foundry",
]

[[sections.projects]]
name = "Lighthouse"
url = "https://github.com/sigp/lighthouse"
repos = [
"sigp/lighthouse",
"sigp/discv5",
]

[[sections.projects]]
name = "Rust Ethereum"
url = "https://github.com/rust-bitcoin"
repos = [
"rust-ethereum/ethabi",
"rust-ethereum/enr",
"rust-ethereum/devp2p",
"rust-ethereum/dnsdisc",
]

[[sections.projects]]
name = "Rust Web3"
url = "https://github.com/tomusdrw/rust-web3"
repos = [
"tomusdrw/rust-web3",
]

[[sections.projects]]
name = "zkSync"
url = "https://github.com/matter-labs/zksync"
repos = [
"matter-labs/zksync",
"matter-labs/compiler-solidity",
]
